In [1]:
import numpy as np

In [2]:
class perceptron:
    def __init__(self, w1, w2, bias, activation=True):
        self.w1 = w1
        self.w2 = w2
        self.bias = bias
        self.activation = activation
        
    def __call__(self, x1, x2):
        y = x1*self.w1 + x2*self.w2 + self.bias
        if self.activation:
            # step function
            if y > 0:
                return 1
            else:
                return 0
        else:
            return y

In [3]:
x1 = -0.7
x2 = 0.3

In [4]:
perceptron1 = perceptron(-0.1, 0.2, 0.3)
perceptron2 = perceptron(0.3, -0.1, -0.1)
perceptron3 = perceptron(0.2, 0.7, -0.3)

In [5]:
a1 = perceptron1(x1, x2)
a2 = perceptron2(x1, x2)
a3 = perceptron2(x1, x2)
print('일반 연산:', a1, a2, a3)

일반 연산: 1 0 0


In [6]:
X = np.array([-0.7, 0.3])

In [13]:
X.shape

(2,)

In [8]:
W = np.array([[-0.1, 0.3, 0.2], [0.2, -0.1, 0.7]])

In [12]:
W.shape

(2, 3)

In [10]:
B = np.array([0.3, -0.1, -0.3])

In [14]:
B.shape

(3,)

In [15]:
X@W + B

array([ 0.43, -0.34, -0.23])

In [16]:
def step_function(x):
    y = x > 0
    return y.astype(np.int64)

In [17]:
step_function(X@W + B)

array([1, 0, 0], dtype=int64)

# 복잡한 네트워크 구현

In [25]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [32]:
def identity_function(x):
    return x

In [19]:
X = np.array([1.0, 0.5]) # 1행 2열
print(X, X.shape)

[1.  0.5] (2,)


In [23]:
W1 = np.array([[0.1, 0.3, 0.5],
              [0.2, 0.4, 0.6]])
print(W1, W1.shape)

[[0.1 0.3 0.5]
 [0.2 0.4 0.6]] (2, 3)


In [24]:
B1 = np.array([0.1, 0.2, 0.3])
print(B1, B1.shape)

[0.1 0.2 0.3] (3,)


In [27]:
Z1 = X@W1 + B1
print(Z1, Z1.shape)

[0.3 0.7 1.1] (3,)


In [28]:
A1 = sigmoid(Z1)
print(A1, A1.shape)

[0.57444252 0.66818777 0.75026011] (3,)


In [29]:
W2 = np.array([[0.1, 0.4],
               [0.2, 0.5],
               [0.3, 0.6]])
print(W2, W2.shape)

[[0.1 0.4]
 [0.2 0.5]
 [0.3 0.6]] (3, 2)


In [30]:
B2 = np.array([0.1, 0.2])
print(B2, B2.shape)

[0.1 0.2] (2,)


In [31]:
Z2 = A1@W2 + B2
A2 = sigmoid(Z2)
print(A2, A2.shape)

[0.62624937 0.7710107 ] (2,)


In [33]:
W3 = np.array([[0.1, 0.3],
               [0.2, 0.4]])
B3 = np.array([0.1, 0.2])
print(W3, B3)

[[0.1 0.3]
 [0.2 0.4]] [0.1 0.2]


In [34]:
Z3 = A2@W3 + B3
Y  = identity_function(Z3)

In [35]:
print(Y)

[0.31682708 0.69627909]


# 함수화

In [36]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5],[0.2, 0.4, 0.6]])
    network['B1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4],[0.2, 0.5],[0.3, 0.6]])
    network['B2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3],[0.2, 0.4]])
    network['B3'] = np.array([0.1, 0.2])
    return network

In [41]:
def forward(network, x):
    Z1 = sigmoid(x@network['W1'] + network['B1'])
    Z2 = sigmoid(Z1@network['W2'] + network['B2'])
    Y  = identity_function(Z2@network['W3'] + network['B3'])
    return Y

In [42]:
network = init_network()

In [43]:
x = np.array([1.0, 0.5])

In [44]:
y = forward(network, x)

In [45]:
print(y)

[0.31682708 0.69627909]
